### PR TITLE
adding Symfony2cheatsheet website

### PR DESCRIPTION
**Pull request by rozehnal**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
It's looks like quite old stuff. Last mentioned version 2.2, which is deprecated for 2 years.

I'd like to keep list up to date (moreover stuffs like cheatsheets covering whole project), so people won't get confused.

**Comment by rozehnal** [comment]
Agree, it's getting to be outdated ... but still very usefull for me.

**Comment by TomasVotruba** [comment]
@rozehnal What version do you work with? Did you meet some BC breaks with never versions?

**Comment by rozehnal** [comment]
I'm on 2.6 still... The mentioned notes usually uses just basic constructions having good back compatibility in Symfony - so I don't know about any. If you find something wrong just fork and make PR :-)

**Comment by TomasVotruba** [comment]
> If you find something wrong just fork and make PR :-)

Good idea. Where is the repo?

**Comment by rozehnal** [comment]
Just open http://www.symfony2cheatsheet.com and at the right upper corner "Fork me on Github".

**Comment by TomasVotruba** [comment]
I see. Haven't noticed in all those informations.

Thanks for contribution! Merged.

**Pull request merged**
